### ISSUE TITLE
Compatibility to php 3.2

### ISSUE THREAD

**Issue by Hideman85** [o0johntam0o/phpBB-Extension-Codebox-Plus#15]
I test your new version on my forum and have just one probleme ...
I find it and correct it : 
In routing.yml you have : 

```
o0johntam0o_codeboxplus_base_controller:
    pattern: /codeboxplus
    defaults: { _controller: o0johntam0o.codeboxplus.controller:base }

o0johntam0o_codeboxplus_download_controller:
    pattern: /codeboxplus/download/{id}-{part}
    defaults: { _controller: o0johntam0o.codeboxplus.controller:downloader, id:0, part:0 }
    requirements:
        id: \d+
        part: \d+
```

And you need : 

```
o0johntam0o_codeboxplus_base_controller:
    path: '/codeboxplus'
    defaults: { _controller: 'o0johntam0o.codeboxplus.controller:base' }

o0johntam0o_codeboxplus_download_controller:
    path: '/codeboxplus/download/{id}-{part}'
    defaults: { _controller: 'o0johntam0o.codeboxplus.controller:downloader', id:0, part:0 }
    requirements:
        id: \d+
        part: \d+
```

So you just need to create an other branch to apply change ....

Thanks for you for your update ;)
